### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by tcjr** [nag5000/ember-tippy#4]
Using this addon with  a recent version (e.g., 3.2.7) of `ember-modifier` causes deprecation warnings in the browser console:

```
DEPRECATION: ember-modifier (in TippyForComponentModifier at Error
    at TippyForComponentModifier.get [as args] (http://app-dev.casefleet.com:4200/assets/chunk.541afd1ad2a37e977a6e.js:106312:181)
    at get options [as options] (http://app-dev.casefleet.com:4200/assets/chunk.541afd1ad2a37e977a6e.js:120639:15)
    at TippyForComponentModifier.didInstall (http://app-dev.casefleet.com:4200/assets/chunk.541afd1ad2a37e977a6e.js:120964:44)
    at ClassBasedModifierManager.installModifier (http://app-dev.casefleet.com:4200/assets/chunk.541afd1ad2a37e977a6e.js:105946:16)
    at CustomModifierManager.install (http://app-dev.casefleet.com:4200/assets/vendor.js:56395:18)
    at http://app-dev.casefleet.com:4200/assets/vendor.js:66166:25
    at track (http://app-dev.casefleet.com:4200/assets/vendor.js:70551:7)
    at TransactionImpl.commit (http://app-dev.casefleet.com:4200/assets/vendor.js:66165:42)
    at EnvironmentImpl.commit (http://app-dev.casefleet.com:4200/assets/vendor.js:66262:19)
    at inTransaction (http://app-dev.casefleet.com:4200/assets/vendor.js:66287:13)): using `this.args` is deprecated. Access positional and named arguments directly in the `modify` hook instead.
```

and

```
(stack trace removed)
The `didInstall`, `didReceiveArguments`, and `didUpdateArguments` hooks are deprecated. Use the new `modify` hook instead. [deprecation id: ember-modifier.use-modify]
```

and

```
(stack trace removed)
using `this.element` is deprecated. Access the `element` as an argument in the `modify` hook instead. [deprecation id: ember-modifier.no-element-property]
```

and

```
(stack trace removed)
`willDestroy`, `isDestroyed`, and `isDestroyed` are deprecated. Use the corresponding API from '@ember/destroyable' instead. [deprecation id: ember-modifier.use-destroyables]
```

We get all these deprecations for a single `<Tippy>` usage -- they _really_ want you to use the new API.

The release of version 4 of `ember-modifier` is imminent, so I think apps using that version won't be able to use this addon.

**Comment by donaldsonjulia** [comment]
@nag5000 Would love to see this PR merged please! We can no longer use `ember-tippy` due to the deprecations of `ember-modifier`. This PR fixes all issues and restores functionality. :)
